[book]
title = "matrix-media-repo"
author = "t2bot.io"
description = "Information for matrix-media-repo"
src = "."

[build]
build-dir = "../books/matrix-media-repo"
create-missing = true

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = []
git-repository-url = "https://github.com/t2bot/docs.t2bot.io/tree/main/matrix-media-repo"
